# ---- user's settings -------------------------------------------------------

TARGET      = test.dll
FAR_EXPORTS = OPEN
SRCDIR      = ..\..\!far_src
FARDIR      = $(SRCDIR)

# ---- end of user's settings ------------------------------------------------
include $(SRCDIR)\plugins\luamacro\luafar\luaplug.mak

# (end of Makefile)
